version: "3.9"
services:
  web:
    container_name: ${WEB_SERVER_NAME}
    build: ./docker/nginx
    volumes:
      - ./back:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - "${WEB_SERVER_PORT}:80"
    working_dir: /var/www
    command: /bin/sh -c "DOLLAR=$$ envsubst < /etc/nginx/templates/default.conf > /etc/nginx/conf.d/default.conf ; nginx -g 'daemon off;'"
    environment:
      APP_SERVER_NAME: ${APP_SERVER_NAME}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    depends_on:
      - app
  app:
    container_name: ${APP_SERVER_NAME}
    build: ./docker/php
    volumes:
      - ./back:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www

networks:
  default:
    driver: bridge
